name: Deployment (Production)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM packages
        run: yarn install
      - name: Build dist
        run: yarn dist
      - name: Deploy documentation
        run: yarn deploy --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Release to npm
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
